from __future__ import annotations

from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches, Pt

from services.config_loader import load_yaml


def _add_footer(slide, text: str) -> None:
    box = slide.shapes.add_textbox(Inches(0.4), Inches(7.05), Inches(12.5), Inches(0.25))
    frame = box.text_frame
    frame.text = text
    frame.paragraphs[0].font.size = Pt(8)


def _summary(rows: list[dict]) -> dict:
    brands = Counter(brand for row in rows for brand in row.get("brands", []))
    samsung = brands.get("Samsung", 0)
    total = sum(brands.values())
    competitors = total - samsung
    top_competitor = "-"
    for brand, count in brands.most_common():
        if brand != "Samsung":
            top_competitor = f"{brand} ({count})"
            break
    retailers = Counter(row.get("retailer", "") for row in rows)
    return {
        "total": total,
        "samsung": samsung,
        "competitors": competitors,
        "share": round((samsung / total) * 100, 1) if total else 0,
        "top_competitor": top_competitor,
        "retailers": retailers,
        "brands": brands,
    }


def generate_ppt(category: str, rows: list[dict], output_path: Path, week: int) -> Path:
    style = load_yaml("config/ppt_style.yaml").get("style", {})
    prs = Presentation()
    prs.slide_width = Inches(float(style.get("slide_width", 13.333)))
    prs.slide_height = Inches(float(style.get("slide_height", 7.5)))
    summary = _summary(rows)

    slide = prs.slides.add_slide(prs.slide_layouts[6])
    title = slide.shapes.add_textbox(Inches(0.6), Inches(0.7), Inches(12), Inches(1.0))
    title.text_frame.text = f"Leaflet W{week:02d} {category} Report"
    title.text_frame.paragraphs[0].font.size = Pt(36)
    subtitle = slide.shapes.add_textbox(Inches(0.6), Inches(1.8), Inches(12), Inches(0.5))
    subtitle.text_frame.text = f"Generated {date.today().isoformat()}"
    _add_footer(slide, style.get("footer_text", "Generated by Leaflet Monitoring Tool"))

    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Summary"
    table = slide.shapes.add_table(6, 2, Inches(0.7), Inches(1.3), Inches(5.8), Inches(2.6)).table
    metrics = [
        ("Total brand appearances", summary["total"]),
        ("Samsung appearances", summary["samsung"]),
        ("Competitor appearances", summary["competitors"]),
        ("Samsung share %", f'{summary["share"]}%'),
        ("Top competitor", summary["top_competitor"]),
        ("Pages/products detected", len(rows)),
    ]
    for idx, (label, value) in enumerate(metrics):
        table.cell(idx, 0).text = str(label)
        table.cell(idx, 1).text = str(value)

    if summary["brands"]:
        chart_data = CategoryChartData()
        chart_data.categories = list(summary["brands"].keys())
        chart_data.add_series("Appearances", list(summary["brands"].values()))
        slide.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, Inches(7), Inches(1.2), Inches(5.7), Inches(3.5), chart_data)
    _add_footer(slide, style.get("footer_text", "Generated by Leaflet Monitoring Tool"))

    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Retailer Activity"
    activity = slide.shapes.add_table(max(len(summary["retailers"]), 1) + 1, 2, Inches(0.7), Inches(1.3), Inches(6), Inches(3)).table
    activity.cell(0, 0).text = "Retailer"
    activity.cell(0, 1).text = "Included pages/products"
    for idx, (retailer, count) in enumerate(summary["retailers"].items(), start=1):
        activity.cell(idx, 0).text = retailer
        activity.cell(idx, 1).text = str(count)
    _add_footer(slide, style.get("footer_text", "Generated by Leaflet Monitoring Tool"))

    grouped = defaultdict(list)
    for row in rows:
        grouped[row.get("retailer", "")].append(row)
    for retailer, retailer_rows in grouped.items():
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = retailer
        x, y = Inches(0.5), Inches(1.1)
        for row in retailer_rows[:4]:
            image_path = row.get("image_path")
            if image_path and Path(image_path).exists():
                slide.shapes.add_picture(image_path, x, y, height=Inches(2.5))
            notes = slide.shapes.add_textbox(x, y + Inches(2.6), Inches(3), Inches(0.6))
            notes.text_frame.text = row.get("comment") or f"Page {row.get('page_number')} | {', '.join(row.get('brands', []))}"
            x += Inches(3.2)
        _add_footer(slide, f"Source: {retailer_rows[0].get('source_label', retailer)} | {style.get('footer_text', '')}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    prs.save(output_path)
    return output_path
