brands:
  - Samsung
  - LG
  - Hisense
  - Haier
  - TCL
  - Beko
  - Bosch
  - Whirlpool
  - Candy
  - Midea
  - Xiaomi
  - Apple
  - Oppo
  - Honor
  - Infinix
  - Realme
  - Taurus
  - Siera
  - Sinken
  - Philips
  - Sony
  - Panasonic
